#!/bin/bash

FOREGROUND=$(xrdb -query | grep 'color12:'| awk 'NR==1{print $NF}')
RED=$(xrdb -query | grep 'color1:'| awk 'NR==1{print $NF}')
OLR_RED="#e53714"
ROFI_OPTIONS=(-theme $HOME/.config/rofi/rofi_full -font "Monoisome 16" -fullscreen 0 -theme-str "*{accent: $FOREGROUND;}")

another=$(echo " RELOAD
 LOCK
 LOGOUT
 REBOOT
 POWOFF" | awk '{print $(NF1)}' | rofi "${ROFI_OPTIONS[@]}" -dmenu -i -p "SYSTEM: ")

if [ "$another" == "RELOAD" ] ; then
	i3-msg reload;
	i3-msg restart;
	res
	i3working

elif [ "$another" == " LOCK" ] ; then
	exec /home/taurthil/.local/bin/lock-theme;

elif [ "$another" == " LOGOUT" ] ; then
	[ $(echo -e "Yes\nNo" | rofi "${ROFI_OPTIONS[@]}" -theme-str "*{accent: $RED;}" -dmenu -i -p "Are you shure you want to proceed?") == Yes ] && i3-msg exit || bspc quit
	
elif [ "$another" == " REBOOT" ] ; then
	[ $(echo -e "Yes\nNo" | rofi "${ROFI_OPTIONS[@]}" -theme-str "*{accent: $RED;}" -dmenu -i -p "Are you shure you want to proceed?") == Yes ] && reboot
	
elif [ "$another" == " POWOFF" ] ; then
	[ $(echo -e "Yes\nNo" | rofi "${ROFI_OPTIONS[@]}" -theme-str "*{accent: $RED;}" -dmenu -i -p "Are you shure you want to proceed?") == Yes ] && poweroff

else
    echo $another
fi
